services:
  app:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./model_artifacts:/app/model_artifacts
      - ./app.py:/app/app.py
      - ./responsible_ai:/app/responsible_ai
      - ./training:/app/training
      - ./ml_pipeline:/app/ml_pipeline
